language: java

jdk:
  - openjdk8

services:
  - docker

addons:
  sonarcloud:
    organization: "gauket-github"
    token:
      secure: ${SONAR_TOKEN}

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

before_install:
    - ./gradlew clean build
    - docker build -t aphv/demo-review .
    - docker run -t -d --name aphv-demo-review -p 8080:8080 --restart=always -ti aphv/demo-review
    - docker ps -a

script:
  - ./gradlew sonarqube
