language: java

jdk:
  - openjdk8

services:
  - docker

before_install:
  - ./gradlew clean build
  - docker build -t aphv/demo-review .
  - docker run -t -d --name aphv-demo-review -p 8181:8080 --restart=always -ti aphv/demo-review
  - docker ps -a

addons:
  sonarcloud:
    organization: "gauket-github"

script:
  - sonar-scanner
